### ISSUE TITLE
Feature Request: Add a setting to adjust the screen to the lowest brightness when the screen is always on

### ISSUE THREAD

**Issue by C1og** [elastic-rock/KeepScreenOn#22]
Use case: Some apps need to keep the screen always on in order to run stably in the background, and reduce battery consumption.
It would be even better if the previous brightness level could be restored when the "always on" mode is turned off.

Thank you for developing such a useful app.

**Comment by elastic-rock** [comment]
A small rant at the beginning: I personally really don't like when code has to be developed in order to compensate for the incapability of some large corporations to develop working software. 🙁 

Indeed, there are apps for which the screen has to be maintained on in order prevent them from going in the background where they stop doing whatever you want them to do. However, I don't think it is that big of a hassle to decrease the brightness and then increase it back again once the app has finished its thing. Regardless, app developers should do their work in the first place. You want to be able to do other stuff whilst the thing works in the background instead of having to wait.

Nevertheless, feel free to prove me wrong and convince me that this is a worthy feature. I am open to reconsider my opinion. 🙂
