### ISSUE TITLE
[Feature Request] keep the device awake, showing a black screen on the display

### ISSUE THREAD

**Issue by Bhardwaj10Ankit** [elastic-rock/KeepScreenOn#27]
It would be really great if a feature to keep the device awake, showing a black screen on the display like [Blekip](https://play.google.com/store/apps/details?id=in.krosbits.blekip) can be introduced.

**Comment by elastic-rock** [comment]
I understand the use case but the main idea of this app is to keep the screen on not off. 🙂

What I don't like is that this is a solution to apps that are not well programmed. Critical tasks should be run as foreground services so that they are not interrupted if the screen turns off. One could say, "What about YouTube?", but my answer to that would be to use [Newpipe](https://github.com/TeamNewPipe/NewPipe) which allows you to run videos in the background.

What are your reasons for requestong the feature?

**Comment by Bhardwaj10Ankit** [comment]
Generally I use the app "Blekip" for the incidents in which I need to keep my screen on but don't want to waste my battery, like while downloading big Files, or sharing large files using apps like LocalSend and few other similar  use cases where app needs to be kept on screen for a longer period to ensure the success of task ( don't want to risk it by sending the app in background) ........ 
BTW I really like Blekip it has very clean UI for the use case but I'd love if the feature gets introduced in KeepScreenOn. 
Please consider it 🙏🏻

**Comment by elastic-rock** [comment]
1. As already said, the goal of this app is to keep the screen on and so such a feature would go completely against the fundamental philosophy of KeepScreenOn 🙂 
2. I am not a fan of creating software that fixes other software, so I advise you to contact the developer to implement background work (LocalSend is open source so it shouldn't be a problem)
3. You already have Blekip so you might aswell continue using it 😀 

I am sorry but this feature will not be implemented.
