### ISSUE TITLE
Option to hide app icon

### ISSUE THREAD

**Issue by VasilisKos** [elastic-rock/KeepScreenOn#3]
Add a toggle in the app window, to hide the app icon in the app drawer. It's useless after the initial start of the app. If someone wants to launch the app, he can do it by long tapping the tile, and then tap "launch" in the app settings.

**Comment by elastic-rock** [comment]
I agree on that one. :) Will get to work as soon as I can.

**Comment by elastic-rock** [comment]
Firstly, turns out it is quite tricky to hide the app icon whilst still being able to open it from elsewhere as noted in the [android documentation](https://developer.android.com/reference/android/content/pm/LauncherApps#getActivityList(java.lang.String,%20android.os.UserHandle)) and [here](https://stackoverflow.com/questions/19114439/android-hide-unhide-app-icon-programmatically). Secondly, there could be users who would hide the app icon and then have no idea that they can long press the tile to open the app itself. This would become even more notable if features like https://github.com/elastic-rock/KeepScreenOn/issues/9 and https://github.com/elastic-rock/KeepScreenOn/issues/10 that would have a setting in the app get implemented, since people would actually have an incentive to visit the app. To clarify, the reason the app icon is hidden in @Wjxfi 's project is because it is hidden all the time which is something I do not want to do, as it would be again confusing for people if they install an app and there is no app icon. Therefore I will not work on this.

**Comment by VasilisKos** [comment]
> Firstly, turns out it is quite tricky to hide the app icon whilst still being able to open it from elsewhere as noted in the [android documentation](https://developer.android.com/reference/android/content/pm/LauncherApps#getActivityList(java.lang.String,%20android.os.UserHandle)) and [here](https://stackoverflow.com/questions/19114439/android-hide-unhide-app-icon-programmatically). Secondly, there could be users who would hide the app icon and then have no idea that they can long press the tile to open the app itself. This would become even more notable if features like #9 and #10 that would have a setting in the app get implemented, since people would actually have an incentive to visit the app. To clarify, the reason the app icon is hidden in @Wjxfi 's project is because it is hidden all the time which is something I do not want to do, as it would be again confusing for people if they install an app and there is no app icon. Therefore I will not work on this.

I would only agree with you if you plan to add settings. Then it would make sense. Far from that, I don't agree with the rest arguments. But, it's up to you anyway.

**Comment by elastic-rock** [comment]
I still feel that most people expect apps to have icons, even if they are tech-savvy. I would nonetheless argue that an icon on the home screen or in the navigation drawer is not that big of a deal.
